name: Deploy to cPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
    - uses: actions/checkout@v4
    
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }} 
        username: ${{ secrets.FTP_USERNAME }} 
        password: ${{ secrets.FTP_PASSWORD }}
